# Default CI build
# restore --> build --> test --> pack
# Triggers on PR's to protected branches.
# Artifact to preserve packages.
#
name: build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - development
env:
  PackTarget: src/kwld.Xunit.Ordering
defaults:
  run: 
    shell: pwsh
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build and test"
    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    
    - name: Restore dependencies
      run: dotnet restore --locked-mode src/

    - name: Build
      run: >
       dotnet build 
       -c Release
       --no-restore        
       -p:ContinuousIntegrationBuild=true
       src/ 

    - name: Test
      run: >
        dotnet test
        -c Release
        --no-build
        --verbosity normal
        --logger trx 
        --results-directory "TestResults" 
        src/

    - name: Pack 
      run: >
        dotnet pack
        -c Release
        --no-build
        -o ./packages 
        ${{env.PackTarget}}

    - name: Keep package artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: packages/
        if-no-files-found: error
  